Set up nix for local development
helsing-ai/atmosphere pull request #23
Opened 2024-04-25 08:26 UTC by ulucs

2024-04-25 11:41 UTC, poliorcetics requested changes
I think this flake is more complicated than necessary: e.g., why do we need `perSystem`: flake are already system-specific by default.

2024-04-25 11:41 UTC, poliorcetics commented on flake.nix
> +  description = "A demo of sqlite-web and multiple postgres services";
Copy pasted description

2024-04-25 11:41 UTC, poliorcetics commented on flake.nix
> +                darwin.apple_sdk.frameworks.SystemConfiguration
We should only add those when launching the flake on macos

2024-04-25 11:41 UTC, poliorcetics commented on flake.nix
> +    rust-overlay.url = "github:oxalica/rust-overlay";
Those should be made to follow `nixpkgs` to avoid having several versions of it in the lock and thus the store.

2024-04-25 12:23 UTC, ulucs commented on flake.nix
> +    rust-overlay.url = "github:oxalica/rust-overlay";
I found out that only rust-overlay depends on nixpkgs and added the follows; but it also depends on systems through flake-utils, but I could not get the sub-dependency to follow the systems input, do you have any idea why this can be happening?

```
    rust-overlay = {
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.inputs.systems.follows = "systems";
      url = "github:oxalica/rust-overlay";
    };
```

```
Inputs:
├───flake-parts: github:hercules-ci/flake-parts/9126214d0a59633752a136528f5f3b9aa8565b7d?narHash=sha256-sB4SWl2lX95bExY2gMFG5HIzvva5AVMJd4Igm%2BGpZNw%3D (2024-04-01 23:40:58)
│   └───nixpkgs-lib: github:NixOS/nixpkgs/d8fe5e6c92d0d190646fb9f1056741a229980089?dir=lib&narHash=sha256-iMUFArF0WCatKK6RzfUJknjem0H9m4KgorO/p3Dopkk%3D (2024-03-29 09:07:56)
├───nixpkgs: github:nixos/nixpkgs/a0cadba85e907b8e2d6ae549d25535da3b1b6d5e?narHash=sha256-kiNvy1g5tyC6ZItTbPmFUnSug4t/I4bLne9OdKnd4sM%3D (2024-04-24 14:24:25)
├───process-compose-flake: github:Platonic-Systems/process-compose-flake/ee8cd505f08f6cd691930e70987a306b7726851b?narHash=sha256-pQIg3wrNBDdRiuhcVC8DFmTXK8GHtR%2BiV%2B5Gvsozx5s%3D (2024-04-24 01:04:55)
├───rust-overlay: github:oxalica/rust-overlay/8a2edac3ae926a2a6ce60f4595dcc4540fc8cad4?narHash=sha256-kOeyS3GFwgnKvzuBMmFqEAX0xwZ7Nj4/5tXuvpZ0d4U%3D (2024-04-24 02:13:43)
│   ├───flake-utils: github:numtide/flake-utils/b1d9ab70662946ef0850d488da1c9019f3a9752a?narHash=sha256-SZ5L6eA7HJ/nmkzGG7/ISclqe6oZdOZTNoesiInkXPQ%3D (2024-03-11 08:33:50)
│   │   └───systems: github:nix-systems/default/da67096a3b9bf56a91d16901293e51ba5b49a27e?narHash=sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768%3D (2023-04-09 08:27:08)
│   └───nixpkgs follows input 'nixpkgs'
├───services-flake: github:juspay/services-flake/4a48d4a7b9a6144a48239bf62a278ca922df98e1?narHash=sha256-83fde6KOfQfGhFg/HAyBsENg%2Bgxq89sog/DvFXOceoU%3D (2024-04-22 10:29:11)
└───systems: github:nix-systems/default/da67096a3b9bf56a91d16901293e51ba5b49a27e?narHash=sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768%3D (2023-04-09 08:27:08)
```

2024-04-25 14:39 UTC, ulucs commented on flake.nix
> +    rust-overlay.url = "github:oxalica/rust-overlay";
yes, that worked!

2024-04-26 09:55 UTC, poliorcetics commented
Is this still a draft ?

2024-04-29 12:49 UTC, poliorcetics approved these changes

2024-04-29 12:51 UTC, merged